In [7]:
import pandas as pd
from sqlalchemy import create_engine
import pandas as pd
from bs4 import BeautifulSoup
import requests

In [3]:
# Import NYT best sellers from 2011 to 2018.
# Source: https://data.world/typhon/new-york-times-bestsellers-from-2011-to-2018/workspace/file?filename=books_uniq_weeks.csv
nyt_bestsellers = "books_uniq_weeks.csv"
nyt_df = pd.read_csv(nyt_bestsellers)
nyt_df.head()

,publisher,dagger,book_review_link,author,primary_isbn10,price,primary_isbn13,sunday_review_link,date,first_chapter_link,contributor,title,age_group,weeks_on_list
0,Riverhead,0,https://www.nytimes.com/2015/01/05/books/the-g...,Paula Hawkins,1594634025,0,9.78159E+12,https://www.nytimes.com/2015/02/01/books/revie...,2/19/17,NaN,by Paula Hawkins,THE GIRL ON THE TRAIN,NaN,102
1,Scribner,0,NaN,Anthony Doerr,1501173219,0,9.7815E+12,https://www.nytimes.com/2014/05/11/books/revie...,5/7/17,NaN,by Anthony Doerr,ALL THE LIGHT WE CANNOT SEE,NaN,81
2,Vintage,0,NaN,E L James,525431888,0,9.78053E+12,NaN,3/5/17,NaN,by E. L. James,FIFTY SHADES DARKER,NaN,66
3,St. Martin's,0,NaN,Kristin Hannah,1466850604,0,9.78147E+12,NaN,10/29/17,NaN,by Kristin Hannah,THE NIGHTINGALE,NaN,63
4,Penguin Group,0,https://www.nytimes.com/2009/02/19/books/19mas...,Kathryn Stockett,1440697663,0,9.78144E+12,NaN,4/8/12,NaN,by Kathryn Stockett,THE HELP,NaN,58

In [5]:
# Goodreads example URL: 
#https://www.goodreads.com/search?q=1594634025

nyt_df['goodreads_url'] = 'https://www.goodreads.com/search?q=' + nyt_df['primary_isbn10']
nyt_df.head()

,publisher,dagger,book_review_link,author,primary_isbn10,price,primary_isbn13,sunday_review_link,date,first_chapter_link,contributor,title,age_group,weeks_on_list,goodreads_url
0,Riverhead,0,https://www.nytimes.com/2015/01/05/books/the-g...,Paula Hawkins,1594634025,0,9.78159E+12,https://www.nytimes.com/2015/02/01/books/revie...,2/19/17,NaN,by Paula Hawkins,THE GIRL ON THE TRAIN,NaN,102,https://www.goodreads.com/search?q=1594634025
1,Scribner,0,NaN,Anthony Doerr,1501173219,0,9.7815E+12,https://www.nytimes.com/2014/05/11/books/revie...,5/7/17,NaN,by Anthony Doerr,ALL THE LIGHT WE CANNOT SEE,NaN,81,https://www.goodreads.com/search?q=1501173219
2,Vintage,0,NaN,E L James,525431888,0,9.78053E+12,NaN,3/5/17,NaN,by E. L. James,FIFTY SHADES DARKER,NaN,66,https://www.goodreads.com/search?q=525431888
3,St. Martin's,0,NaN,Kristin Hannah,1466850604,0,9.78147E+12,NaN,10/29/17,NaN,by Kristin Hannah,THE NIGHTINGALE,NaN,63,https://www.goodreads.com/search?q=1466850604
4,Penguin Group,0,https://www.nytimes.com/2009/02/19/books/19mas...,Kathryn Stockett,1440697663,0,9.78144E+12,NaN,4/8/12,NaN,by Kathryn Stockett,THE HELP,NaN,58,https://www.goodreads.com/search?q=1440697663

In [ ]:
# Get soup object.

# resp = requests.get("https://www.goodreads.com/search?q=1594634025")
# soup = BeautifulSoup(resp.content, "html.parser")
# print(soup)

def get_html(isbn):
    url = "https://www.goodreads.com/search?q={}".format(isbn)
    resp = requests.get(url)
    soup = BeautifulSoup(resp.content, "html.parser")
    return soup

nyt_df['soup_object'] = nyt_df['primary_isbn10'].map(lambda x: get_html(x))

nyt_df.head()

In [48]:
# Get rating.
rating = soup.find("span", attrs={"itemprop": "ratingValue"})
rating = rating.get_text()
rating = rating.encode("utf-8")
rating = rating.replace('\n', ' ')
rating = float(rating)
print(rating)

3.9

In [49]:
# Get number of ratings.
rating_count = soup.find("meta", attrs={"itemprop": "ratingCount"})
rating_count = rating_count.get_text()
rating_count = rating_count.replace('ratings', '').replace(',', '').strip()
rating_count = int(rating_count)
print(rating_count)

1655858

In [50]:
# Get number of reviews.
reviews = soup.find("meta", attrs={"itemprop": "reviewCount"})
reviews = reviews.get_text()
reviews = reviews.replace('reviews', '').replace(',', '').strip()
reviews = int(reviews)
print(reviews)

103184