In [8]:
import pandas as pd
import numpy as np

file = "Resources/purchase_data.csv"

df = pd.read_csv(file)

## Top Spenders

In [10]:
# Identify top spenders.
top_spenders = df.groupby('SN')['Price'].sum().sort_values(ascending=False).head(5).reset_index()
top_spenders = top_spenders['SN']

# Group the data by user and create aggregate measures.
df_spend = df.groupby(['SN']).agg({'Purchase ID': "count",'Price': ["mean","sum"]}).reset_index()

# Remove multi-level index.
df_spend.columns = [''.join(col).strip() for col in df_spend.columns.values]

# Select only top five spenders.
# df_spend.nlargest(5, pd.to_numeric(df_spend['Pricesum'])) 

# Format values. Make them pretty!
df_spend["Pricemean"] = df_spend["Pricemean"].map("${:.2f}".format)
df_spend["Pricesum"] = df_spend["Pricesum"].map("${:.2f}".format)

# Rename columns. Why does this not work consistently?
df_spend.rename(columns={'Purchase IDcount':'Purchase Count','Pricemean':"Average Purchase Price","Pricesum":"Total Purchase Value"})

# Subset to look at only top spenders.
df_spend[df_spend['SN'].isin(top_spenders)].sort_values('Pricesum',ascending=False)

type(df_spend)

pandas.core.frame.DataFrame

In [13]:
# TUTOR - lambda vs apply vs map vs query vs filter.
# TUTOR - Tell me about the dataframegroupby object.

#Identify top five selling items and store them in a list.
top_five = df['Item Name'].value_counts().sort_values(ascending=False).head(5).reset_index()
top_five = top_five['index'].tolist()

# Filter dataframe for only items in top five.
top_five_df = df[['Item ID','Item Name','Price']].loc[df['Item Name'].isin(top_five)]

print(type(top_five_df))
top_five_df.head()

<class 'pandas.core.frame.DataFrame'>

    Item ID                                     Item Name  Price
0       108     Extraction, Quickblade Of Trembling Hands   3.53
2        92                                  Final Critic   4.88
24      141                                    Persuasion   3.19
25      178  Oathbreaker, Last Hope of the Breaking Storm   4.23
56      108     Extraction, Quickblade Of Trembling Hands   3.53

In [23]:
# TUTOR - Why does groupby not work here? Neither does "head"
top_five_df_groupby = top_five_df.groupby('Item ID')
top_five_df_groupby.head(5)

     Item ID                                     Item Name  Price
2         92                                  Final Critic   4.88
18        82                                       Nirvana   4.90
24       141                                    Persuasion   3.19
25       178  Oathbreaker, Last Hope of the Breaking Storm   4.23
61       178  Oathbreaker, Last Hope of the Breaking Storm   4.23
62       178  Oathbreaker, Last Hope of the Breaking Storm   4.23
72       178  Oathbreaker, Last Hope of the Breaking Storm   4.23
88        82                                       Nirvana   4.90
98       141                                    Persuasion   3.19
99       101                                  Final Critic   4.19
132      145                          Fiery Glass Crusader   4.58
202       82                                       Nirvana   4.90
207      145                          Fiery Glass Crusader   4.58
222      178  Oathbreaker, Last Hope of the Breaking Storm   4.23
240       82                                       Nirvana   4.90
247       82                                       Nirvana   4.90
252       92                                  Final Critic   4.88
261      141                                    Persuasion   3.19
273       92                                  Final Critic   4.88
277       92                                  Final Critic   4.88
329      145                          Fiery Glass Crusader   4.58
411      101                                  Final Critic   4.19
438      145                          Fiery Glass Crusader   4.58
474      145                          Fiery Glass Crusader   4.58
536      101                                  Final Critic   4.19
538      141                                    Persuasion   3.19
587      141                                    Persuasion   3.19
608      132                                    Persuasion   3.33
651      132                                    Persuasion   3.33
712       92                                  Final Critic   4.88
774      101                                  Final Critic   4.19
778      101                                  Final Critic   4.19

In [22]:
import pandas as pd
import numpy as np

file = "Resources/purchase_data.csv"

df = pd.read_csv(file)

# TUTOR - How would you have used lambda or apply in coordination with the list of top items?
print(type(df))

example = df[['Item ID','Item Name','Price']].groupby(['Item ID']).sort_values(by='Item ID')
# You can't sort values since it's a DataFrameGroupBy object: .sort_values(by='Item ID')
print(type(example))

example.head()
#Example code: print(groups.apply(lambda g: g[g['B'] == g['B'].max()]))

<class 'pandas.core.frame.DataFrame'>

AttributeError: Cannot access callable attribute 'sort_values' of 'DataFrameGroupBy' objects, try using the 'apply' method